

spring.data.mongodb.uri=mongodb+srv://shalinimano2595_db_user:shalini@cluster0.ugxq9tg.mongodb.net/newsletter_db_test

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000

logging.level.com.newsletter=WARN
logging.level.org.springframework.data.mongodb=WARN
